# Generated by Django 5.1.3 on 2024-12-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineed', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='damagedProperty',
            field=models.CharField(choices=[('chair', 'Chair'), ('table', 'Table'), ('electricfan', 'Electric Fan'), ('outlet', 'Outlet'), ('television', 'Television'), ('whiteboard', 'Whiteboard'), ('tiles', 'Tiles'), ('window', 'Window')], default='chair', max_length=5000),
        ),
    ]
